import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import React from "react";

type ParameterViewerProps = {
  title: string;
  subtitle: string;
  paramsJSON: string | null;
  variant?: "input" | "textarea";
};

function ParameterViewer({
  title,
  subtitle,
  paramsJSON,
  variant = "input",
}: ParameterViewerProps) {
  const params = paramsJSON ? JSON.parse(paramsJSON) : null;

  return (
    <Card>
      <CardHeader className="rounded-lg rounded-b-none border-b py-4 bg-gray-50">
        <CardTitle className="text-base">{title}</CardTitle>
        <CardDescription className="text-muted-foreground">
          {subtitle}
        </CardDescription>
      </CardHeader>
      <CardContent className="py-4">
        <div className="flex flex-col gap-2">
          {!params && (
            <p className="text-sm">No parameters generated by this phase</p>
          )}
          {params &&
            Object.entries(params).map(([key, value]) => (
              <div
                key={key}
                className="flex justify-between items-center gap-2"
              >
                <p className="text-sm text-muted-foreground flex-1 basis-1/3">
                  {key}
                </p>
                {variant === "textarea" ? (
                  <Textarea
                    readOnly
                    className="flex basis-2/3"
                    value={value as string}
                  />
                ) : (
                  <Input
                    readOnly
                    className="flex basis-2/3"
                    value={value as string}
                  />
                )}
              </div>
            ))}
        </div>
      </CardContent>
    </Card>
  );
}

export default ParameterViewer;
